---
title: Social Network Analysis - Assignment 2
subtitle: Group 7
date: 2025-11-16
author:
  - name: Floris 	Vermeulen
    affiliations:
      - ref: jads
      - ref: tiu
  - name: Martijn van Iterson
    affiliations:
      - ref: jads
      - ref: tiu
  - name: Niek	Fleerakkers
    affiliations:
      - ref: jads
      - ref: tiu
  - name: Patryk	Grodek
    affiliations:
      - ref: jads
      - ref: tue
  - name: Samir Sabitli
    affiliations:
      - ref: jads
      - ref: tue
affiliations:
  - id: jads
    name: Jheronimus Academy of Data Science
  - id: tiu
    name: Tilburg University
  - id: tue
    name: Eindhoven University of Technology
include-in-header:
  - text: |
      \usepackage{longtable}
      \usepackage{graphicx}
      \usepackage{booktabs}
      \usepackage{dcolumn}
      \usepackage{float}
      \usepackage{listings}
      \usepackage{color}
      \linespread{1.15}
bibliography: resources/r-references.bib
csl: resources/apa-6th-edition.csl
toc: true
toc-depth: 2
format:
  pdf: 
    documentclass: article
    pagesize: a4
    number-sections: true
    df-print: kable
    fig-cap-location: top
    geometry:
      - left=1.15in
      - right=1.15in
      - bottom=1.15in
      - top=1.15in
      - heightrounded
execute:
    echo: false
    cache: true
editor: 
  markdown: 
    wrap: 72
---

```{r}
#| label: analysis-preferences
#| include: false

# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

{{< pagebreak >}}

## Introduction {#sec-intro}

With the advent of online peer-to-peer (P2P) lending platforms, the
traditional methods of financial intermediation have been usurped by
individual choice. The surging popularity and accessibility of services
such as Prosper.com has grown to become one of the most important
avenues through which individuals can secure micro-loans
[@cai_judging_2016]. Arguably, while the democratisation of credit
alleviates numerous pre-existing issues, it serves to exaggerate
well-known informational asymmetries associated with determining
creditworthiness [@mingfeng_lin_social_2009]. Per, @chen_group_2016,
from a traditional financial lens, these asymmetries can contribute to
moral hazard and adverse selection, ultimately causing systemic
financial losses. This arises from the fact the users are anonymous,
challenging the veracity of their information. Further, the unsecured
nature of credit makes its collection relatively ineffective. Jointly,
these factors characterise the lemons market theory by
@akerlof_market_1978.

However, social networks can act a crucial avenue through which
information transfer could be facilitated, alleviate some of the
existing asymmetries [@mingfeng_lin_social_2009]. There are several
prominent theories and research that attempt to bridge this gap. First,
the theory of social capital is particularly salient because it relates
directly to the reputation and trustworthiness of the users
[@adler_social_2002]. While its definition is not strictly defined,
according to @putnam_bowling_2015, it can be seen as a means through
which social organisation facilitate coordination and trust.
@nahapiet_social_1998 define three dimensions, including structural,
relational, and cognitive. We primarily study the structural component,
whereby the network properties relating to tie formation between
borrowers is considered. Following this perspective, @chen_group_2016
argue that social capital is earned through connections to others.
However, per the authors, the internet facilitates weak forms of these
ties, diminishing the benefits of social capital on P2P platforms,
especially for non-friendship networks. Notably, they cite a low
interdependence and closed structures to this effect.

With this, we arrive at our first research problem, aiming to understand
\textbf{to what extent are borrower networks weak in P2P networks?} More
specifically, we formulate the hypothesis

\begin{tabular}{ll}
$\mathrm{\mathbf{H}}_1^a:$ & Borrower networks based on similarity have a low degree of centralisation
\end{tabular}

To understand social capital, we employ techniques related to the
occurance of dyadic connections rather than studying their structural
components. As such, this problem can be studied with the use of the
Quadratic Assignment Procedure (QAP) and Conditional Uniform Graph (CUG)
tests, whereby the theoretical distributions of network characteristics
can be tested.

Our second study attempts to model social capital as a statistical
model, specifically considering the structural dimension to social
capital. According to the comprehensive review of @bachmann_online_2011,
past studies have considered financial, demographic, and soft
informational factors in the financial outcomes of P2P lending, however,
these perspectives have not been considered with relation to each other.
With respect to this premise, we posit
\textbf{what is the role of structural and non-structural factors in the formation of social capital?}
This problem is arguably best studied with the use of Exponential Random
Graph Models (ERGM) as they are considered to work well in identifying a
combination of structural and exogenous patterns in the context of a
variety of network specifications [@jackson_overview_2011].

In studying demographic factors, @pope_whats_2008 suggest that age plays
a significant role in funding success. In particular, compared to
individuals aged 35-60, those aged 35 or younger have a 40-90 basis
point higher success rate. Additionally, those aged 60 and above are
1.1-2.3 percentage points less successful. While this is not a direct
relationship with social capital, it may suggest that these individuals
may be placed lower in the P2P market, per @putnam_bowling_2015.

In studying gender, @barasinska_does_2010 find that female lenders are
less risk averse than male lenders, funding credit with lower interest
rates at a higher frequency. In conjunction, @pope_whats_2008 find that
single women pay 0.4% less interest than men. These factors may indicate
that edges are more likely to form between borrowers if they are women.

The structural dynamics of the network could be explained by the theory
of Relational Herding, as formulated by @de_liu_friendships_2015. The
authors explain that in the face of uncertainty, actors tend to exhibit
a clustering behaviour, even putting aside their own private
information. Though, other social dynamics may also explain the
phenomenon. @devenow_rational_1996 posit that herding may also occur if
individuals blindly follow others without rational analysis. In the P2P
context, @herzenstein_strategic_2011 show evidence of strategic herding
when borrowers observe that a loan has gotten funding in the past.

Further, @podolny_status-based_1993 explains that the ways in which
information flows in social networks can explain its outcomes. In
particular, if the reputation or status of an individual can be
observed, they are said to be "pipes" for other actors to transact with
them. However, if this reputation is merely \textit{perceived}, then it
said to be a "prism". In our context, prism seems more appropriate as
users usually cannot directly observe prestige-related characteristics,
however, this can be tested by constructing a variable related to latent
status.

\begin{table}[h!]
\resizebox{\textwidth}{!}{%
\begin{tabular}{@{}lllll@{}}
\toprule
\textbf{Hypotheses}                                                                                                                                      & \textbf{Type} & \textbf{Dyad}  & \textbf{\begin{tabular}[c]{@{}l@{}}ERGM \\ Term\end{tabular}} & \textbf{Motivation}                                                                                                                                                                                                                                                                                                                  \\ \midrule
\begin{tabular}[c]{@{}l@{}}$\mathrm{\mathbf{H}}^a_2:$ Younger borrowers tend\\ to form more relationships \\ with each other\end{tabular}                & Exogenous     & Independent    & nodecov()                                                     & \begin{tabular}[c]{@{}l@{}}The term captures how the age covariate affects the likelihood \\ of edge formation. Since we want a numeric range, this term is \\ most appropriate.\end{tabular}                                                                                                                                        \\
\begin{tabular}[c]{@{}l@{}}$\mathrm{\mathbf{H}}^a_3:$ Women tend to form more\\ relationships with other borrowers, \\ regardless of gender\end{tabular} & Exogenous     & Independent    & nodefactor()                                                  & \begin{tabular}[c]{@{}l@{}}The term captures the tendency of women to form more edges, \\ regardless of the other gender.\end{tabular}                                                                                                                                                                                               \\
\begin{tabular}[c]{@{}l@{}}$\mathrm{\mathbf{H}}^a_4:$ Borrowers tend to exhibit\\ herding around each other\end{tabular}                                 & Endogenous    & Interdependent & gwesp()                                                       & \begin{tabular}[c]{@{}l@{}}The term captures the tendency for triadic relationships to form. \\ In other words, for ties to form due to the presence of other ties\\ in the dyad's neighbourhood.\end{tabular}                                                                                                                       \\
\begin{tabular}[c]{@{}l@{}}$\mathrm{\mathbf{H}}^a_5:$ Borrowers tend to form ties\\ around other high-status borrowers\end{tabular}                      & Endogenous    & Interdependent & \begin{tabular}[c]{@{}l@{}}gwd() \\ \& nodecov()\end{tabular} & \begin{tabular}[c]{@{}l@{}}The term describes degree distribution, indicating whether a borrower \\ is popular to the degree specified. It does not necessarily \\ relate to community.  It is necessary to also use an indicator of \\ prestige to understand whether pipe or prism dynamics \\ may be more prevalent.\end{tabular} \\ \bottomrule
\end{tabular}%
}
\end{table}

Our research makes notable contributions to existing research on social
network analyses on P2P networks. The study primarily expands upon the
existing ideas of social capital by analysing it with respect to
European P2P lending market and evaluating the interactions between
structural and non-structural factors such as demographics. Typically,
research tends to consider them independently and utilises predictive,
rather than purely statistical models.

Following this, the report will outline the methodology employed. In
this section, we will discuss the dataset utilised, specific data
processing steps and other considerations relating to the empirical or
network environment. Further, we justify the empirical structure of the
analysis, evaluating the specific methodologies utilised with respect to
the wider quantitative landscape. Subsequently, the results are outlined
for each model and hypothesis, alongside their interpretations for our
research problem. Finally, we conclude the report by summarising the
core research problem, our empirical set-up alongside considerations for
future research.

## Methodology {#sec-methodology}

Within this section, we construct the empirical layout of our research
problem, including the dataset and data processing steps.

### Dataset {#sec-dataset}

The study utilises a publicly-retrieved dataset from a leading European
P2P platform called Bondora. The dataset contains detailed information
on both defaulted and non-defaulted loans given to users between
February 2009 and July 2021. Prior to any manipulation, the dataset
contains a range of numeric, binary, categorical, and time-series
attributes across 85,087 unique users and 179,235 individual loans. The
data was originally collected by @noauthor_bondora_nodate in 2021 and
published on kaggle.com. While the user published the data, they simply
downloaded it from a now-defunct page on Bondora's website. Public data
is no longer offered by Bondora, access to newer data is not possible.

\subsection{Data Processing and Network Construction}

To make the data usable for our research, it was processed. The full
steps can be seen in the Appendix. First, only attributes relevant to
the research were kept for resource efficiency and ease of use.
Following this, any rows with missing values were entirely removed to
preserve a complete dataset. This step did not remove a significant
number of data points. Following this, it is mandatory to reduce the
size of the overall dataset to ensure that any analyses conducted can
converge and do so in a timely manner. We did this by randomly removing
data points until the dataset had 500 remaining observations. While a
sampling bias is technically possible as a result, the pseudo-random
data reduction should minimize this effect.

To construct the network, we need to specify edges between users. While
there are many ways to do this, we prefer an approach that does not
introduce unnecessary complexity to models' interpretations and
maintains a meaningful semantic relationship between borrowers.
Ultimately, we create edges based on how similar borrowers are across
several dimensions, computed by cosine similarity. The intuition here
arises from the fact that certain behaviours or social processes
\textit{groups} borrowers together. This technique has the advantage of
discounting vector size for its angle, which reduces the influence of
outliers in defining how similar individuals are. However, to avoid a
fully connected network that would make ERGM completely redundant, we
establish a threshold of `cosine_sim=0.5` to determine whether an edge
can exist. This enables us to control how similar individuals must be
for our analysis while maintaining a reasonable density.

Defining the dimensions that make an individual similar to another is a
difficult task, however, we opted for attributes describing users' loans
rather than their demographic or financial characteristics. This is
\textit{crucial} because we must isolate these variables from any
outcome being studied. Otherwise, our analysis will be severely biased
by data leakage and possibly even simultaneous equation bias. Further,
we chose to standardise the attributes chosen for cosine similarity to
avoid bias introduced by differing variable scales. Ultimately, the
edges formed are weighted
\footnote{We understand that weighted edges make ERGMs significantly more difficult. We can definitely make them binary for further analysis. We believe that making them weighted can make the analysis more meaningful because it would allow us to determine the degree to which a predictor makes someone similar which can be important in determining something like the relational herding or prism/pipe effects. To be discussed.}
by how similar individuals are to each other. The attributes excluded
from this similarity measure were later added to the `igraph` network
object as vertex attributes.

\subsection{Descriptive Statistics and Network Overview}

Having processed the dataset and created a weighted network of similar
borrowers, we provide an overview of the descriptive statistics relating
to the network and wider dataset. The figure below shows an overview of
the network, however, since we rely on sampling for the nodes, the
network is not equivalent to the underlying population. Observing the
figure, we see that there are indeed prevalent communities, however,
there is also significant overlap between them.

[![Plot of the Bondera Network with and without Community
Detection](resources/images/draft_1/duo_network_plot.png){fig-align="left"}](fig:network_plot)

\footnote{We recognise that this reciprocity may not beideal and we are looking for ways to deal with the 100\% reciprocity. Potential point for discussion.}

\begin{table}[h!]
\centering
\caption{Network Descriptive Statistics}
\label{tab:desc}
\begin{tabular}{@{}lr@{}}
\toprule
\textbf{Network Measure} & \textbf{Value} \\ \midrule
Number of Vertices       & 495            \\
Number of Edges          & 14,017         \\
Density                  & 0.109          \\
Reciprocity              & 1.000          \\
Transitivity             & 0.692          \\
Mean Distance            & 2.112          \\ \midrule
Dyad Census: Mutual      & 13,269         \\
Dyad Census: Null        & 108,996        \\ \bottomrule
\end{tabular}
\end{table}

Observing the figure below, we see low betweenness centrality and degree
distribution without any logarithmic adjustments. The latter indicates
that most nodes have very low connectivity. This may have been a result
of the threshold set for the similarity. The former suggests that few
nodes act as the bridge between different communities of borrowers and
that the few highly connected nodes are crucial for the connection of
the wider P2P network.

[![Degree and Betweeness Distribution of the P2P
Network](resources/images/draft_1/deg_bet.png){fig-align="left"}](deg_bet_dist)

The figure below shows various aspects of the wider dataset. Firstly, we
observe that there are significantly more males within our subsample
borrowing than females. Notably, some users did note "Other" for their
gender. It is unclear whether this relates to the user being non-binary
or whether it was a data error. Generally, borrowers tend to be young,
with the median hovering around 22. The interquartile range is
approximately 10 years, suggesting that most users lean younger. The
duration of users' loans tends to be extremely left skewed, indicating
the the majority of users request very long loans. There is quite a
large range in terms of the loan amounts and their interest rates. The
median loan amount hovers around 2000 euros, with most of the users not
borrowing more than 4000. This distribution reaffirms that users prefer
loans on the lower end. For most users, the interest rate is tightly
dispersed and below 40%. This could suggest that loan providers are
quite selective in their clientèle. Notably, some users do exceed 100%
interest rates, suggesting that the data has users with extraordinary
circumstances.

[![Descriptive Statistics of the wider
Dataset](resources/images/draft_1/distributions.png){fig-align="left"}](fig:dists)

\clearpage

## References {.unnumbered}

::: {#refs}
:::

\definecolor{dkgreen}{rgb}{0,0.6,0}
\definecolor{gray}{rgb}{0.5,0.5,0.5}
\definecolor{mauve}{rgb}{0.58,0,0.82}
\lstset{ %
  language=R,                     % the language of the code
  basicstyle=\footnotesize,       % the size of the fonts that are used for the code
  numbers=left,                   % where to put the line-numbers
  numberstyle=\tiny\color{gray},  % the style that is used for the line-numbers
  stepnumber=1,                   % the step between two line-numbers. If it's 1, each line
                                  % will be numbered
  numbersep=5pt,                  % how far the line-numbers are from the code
  backgroundcolor=\color{white},  % choose the background color. You must add 
  showspaces=false,               % show spaces adding particular underscores
  showstringspaces=false,         % underline spaces within strings
  showtabs=false,                 % show tabs within strings adding particular underscores
  frame=false,                   % adds a frame around the code
  rulecolor=\color{black},        % if not set, the frame-color may be changed on line-breaks within not-black text (e.g. commens (green here))
  tabsize=2,                      % sets default tabsize to 2 spaces
  captionpos=b,                   % sets the caption-position to bottom
  breaklines=true,                % sets automatic line breaking
  breakatwhitespace=false,        % sets if automatic breaks should only happen at whitespace
  title=\lstname,                 % show the filename of files included with \lstinputlisting;
                                  % also try caption instead of title
  keywordstyle=\color{blue},      % keyword style
  commentstyle=\color{dkgreen},   % comment style
  stringstyle=\color{mauve},      % string literal style
}
\clearpage
\appendix
\section{Source Code - Data Processing}
\linespread{1}
\lstinputlisting[language=R]{scripts/data_processing_bondora.R}

\clearpage

\section{Source Code - Network Analysis}
\linespread{1}
\lstinputlisting[language=R]{scripts/network_analysis.R}

{{< pagebreak >}}

\linespread{1.15}

## Technology Statement

> During the preparation of this work, we used ChatGPT in order to
> generate select parts of the R script utilised to process the dataset.
> Specifically, the tool was used to transform the processed dataset
> into a format that `igraph` would accept as a network object. No AI
> tool was utilised to write parts of the report. The following parts of
> the assignment were affected/generated by AI tool usage: **DATASET;**
> the data described within this section was processed partly by some
> code drafted by ChatGPT and edited by the group. After using this
> tool/service, **Samir Sabitli** evaluated the validity of the tool’s
> outputs, including the sources that generative AI tools have used, and
> edited the content as needed. As a consequence, **Samir Sabitli**
> takes full responsibility for the content of their work.
